### ISSUE TITLE
Question regarding RL techniques used

### ISSUE THREAD

**Issue by vguillet** [microsoft/AirSim-Drone-Racing-VAE-Imitation#2]
Good afternoon,

I have been reading your paper and going through your code, and the machine learning technique used here still remains slightly unclear to me, could you clarify that? Otherwise congrats, impressive work!

**Comment by rogeriobonatti** [comment]
Hi, we're using imitation learning for learning the motion policy and cross-modal variational auto-encoders for the representation. It might be helpful to look at the paper (https://arxiv.org/abs/1909.06993) and take a look at the references to understand the techniques in depth :)
