### ISSUE TITLE
How to change env.pak file

### ISSUE THREAD

**Issue by hoofreeman** [microsoft/AirSim-Drone-Racing-VAE-Imitation#3]
I have an issue with the env.pak file.
I deploy the project and successfully run the code, then I want to change the soccer.pak to my own env.pak. How to do this? I found some same parts between this project and the drone race project which has three envs, then I unpack the zhangjiaji.pak file, change a little number of files and load the env sucessfully. But when I load my own .pak file, I always failed.This is the part of AirSimExe.log:

[2020.05.14-02.22.06:828][277]LogOutputDevice: Warning: 

Script Stack (0 frames):

[2020.05.14-02.22.06:832][277]LogCore: Error: appError called: Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:/home/madratman/projects/UnrealEngine4.22/UnrealEngine/Engine/Source/Runtime/Core/Public/Containers/Array.h] [Line: 611] 

[2020.05.14-02.22.06:842][277]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x00000000000033fa

[2020.05.14-02.22.06:842][277]LogCore: Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:/home/madratman/projects/UnrealEngine4.22/UnrealEngine/Engine/Source/Runtime/Core/Public/Containers/Array.h] [Line: 611] 

0x0000000002eaee54 AirSimExe!UnknownFunction(0x2caee53)
0x0000000002d3124b AirSimExe!UnknownFunction(0x2b3124a)
0x0000000002cd12b7 AirSimExe!UnknownFunction(0x2ad12b6)
0x0000000002cd10dd AirSimExe!UnknownFunction(0x2ad10dc)
0x0000000005070a6c AirSimExe!UnknownFunction(0x4e70a6b)
0x0000000005080d9a AirSimExe!UnknownFunction(0x4e80d99)
0x000000000508070e AirSimExe!UnknownFunction(0x4e8070d)
0x000000000504aa24 AirSimExe!UnknownFunction(0x4e4aa23)
0x000000000505c390 AirSimExe!UnknownFunction(0x4e5c38f)
0x0000000005067c94 AirSimExe!UnknownFunction(0x4e67c93)
0x0000000004ff9693 AirSimExe!UnknownFunction(0x4df9692)
0x000000000500001c AirSimExe!UnknownFunction(0x4e0001b)
0x0000000002f53a54 AirSimExe!UnknownFunction(0x2d53a53)
0x0000000002f4f0a7 AirSimExe!UnknownFunction(0x2d4f0a6)
0x0000000002f4e9be AirSimExe!UnknownFunction(0x2d4e9bd)
0x0000000002f597d6 AirSimExe!UnknownFunction(0x2d597d5)
0x0000000002f61607 AirSimExe!UnknownFunction(0x2d61606)
0x0000000002f603c5 AirSimExe!UnknownFunction(0x2d603c4)
0x0000000002f6cdc4 AirSimExe!UnknownFunction(0x2d6cdc3)
0x00000000031256bd AirSimExe!UnknownFunction(0x2f256bc)
0x0000000004e6883d AirSimExe!UnknownFunction(0x4c6883c)
0x000000000257864b AirSimExe!UnknownFunction(0x237864a)
0x000000000257ef5a AirSimExe!UnknownFunction(0x237ef59)
0x0000000005d7ae5f AirSimExe!UnknownFunction(0x5b7ae5e)
0x00007f9f4ff97b97 libc.so.6!__libc_start_main(+0xe6)
0x000000000256e029 AirSimExe!UnknownFunction(0x236e028)

[2020.05.14-02.22.06:854][277]LogExit: Executing StaticShutdownAfterError

Thank you!

**Comment by rogeriobonatti** [comment]
@madratman any idea? I haven't tried replacing .paks myself

**Comment by hoofreeman** [comment]
I have solved this problem by not using tha added API in airsimdroneracingvae package.Thanks!
